### ISSUE TITLE
Support override of configuration definitions

### ISSUE THREAD

**Issue by rick-masters** [mikaku/Fiwix#44]
Please support making it easier to customize the configuration of Fiwix from the command line.

The configuration of Fiwix for use with live-bootstrap requires customizing 12 different parameters so it would be helpful to allow specifying this in the build scripts instead of changing the source code.

For example, to use the 2/2 memory split it should be possible to compile like so:
```
gcc -DCONFIG_VM_SPLIT22 ...
```

To use the qemu debug console, it should be possible to compile like so:
```
gcc -DCONFIG_QEMU_DEBUGCON ...
```

To expand a limit, it should be possible to compile like so:
```
gcc -DOPEN_MAX=1536
```

However, these variables cannot be specified at the command line.
Since the latest definition "wins" a definition in a source file takes precedence over a command line option.

A common way to allow command line definitions is to wrap all definitions with #ifndef.
https://stackoverflow.com/questions/41437799/overwrite-a-macro-constant-from-a-makefile

Here is an example config file for a project that does it that way:
https://github.com/gkostka/lwext4/blob/master/include/ext4_config.h
Many examples of this pattern can be found in large C programs.

There are also many variables in Fiwix which have #undef before them. I understand this is to document their existence but an #undef also prevents defining a variable at the command line. A more common method in my experience is to comment out the definition to show that the definition is avaiable but is not defined by default.
For example see FLUSH_ALL_TLBS in this file:
https://github.com/qemu/qemu/blob/master/target/ppc/mmu_helper.c

Finally, it would be helpful if the Makefiles supported passing parameters from the command line to the compiler like so:
```
make CONFFLAGS="-DCONFIG_VM_SPLIT22 -DOPEN_MAX=1536"
```

**Comment by mikaku** [comment]
I see the advantage, the problem is that it creates excessive pollution in the files and reduces a lot the readability. This only a cosmetic problem.

Also there is the issue with the `#undef` constants as they don't follow the same mechanism and are treated in a different way. I see it a bit ugly, but again this is another cosmetic problem.

How does Linux solves this? I mean, I don't follow the modern Linux kernels but I remember that there was a file called `.config` which included all the enabled options. I don't mean to change this PR now, but it's something we can do in the future.

Finally, I'm a bit concerned with the constant `UTS_SYSNAME`. Why do you need to change this one? I mean, the name Fiwix is bound to the copyright line that appears during the boot up of the kernel. If you change the name of the kernel, then there could be a problem with that copyright.

What do you think?

**Comment by mikaku** [comment]
You might want to rebase your PR because of my latest commit 1ee08fc

**Comment by rick-masters** [comment]
After thinking a bit I think you might be happiest with the user_config.h method and that wouldn't be that hard to do. You could keep config.h, limits.h, etc mostly the same.

The downside is that there is an issue if config.h itself *uses* variables because the values may not be "settled" yet. For example NR_FLOCKS uses NR_PROCS, so if user_config.h changes NR_PROCS it should also define NR_FLOCKS appropriately. And user_config.h will have to be maintained to keep up with any new or changed definitions in the future that are dependent on definitions changed in user_config.h.

You've kept config.h fairly clean so this approach should work ok. Some projects have a lot of complicated nested definitions which make it harder to override definitions after the fact in a coherent way.

**Comment by mikaku** [comment]
Thank you for your always very detailed explanations. I really appreciate it.

> ...
> Another alternative would be to allow including overrides at the end of config.h (and limits.h, etc) like so:
>```
>#ifdef USER_CONFIG_H
>#include "user_config.h"
>#endif
>```

I really like this idea. If I understood correctly, it would be as easy to include these thee lines on every header that needs to be overridden during the build, while keeping the readability of the original files. I guess that `Makefile` should always create at least an empty `include/fiwix/user_config.h` file, isn't?

Please, let's take this path, but **only** if this solution won't requires more effort for your work in the live-bootstrap project.

> This doesn't affect your copyright status. The source code is already protected with copyright declarations.

Well, basically I'm concerned about what people will say if they see a live-bootstrap logfile with the following contents:
```
                    Linux kernel v1.4.0 for i386 architecture
                     Copyright (c) 2018-2022, Jordi Sanfeliu

             (built on Mon Oct 30 15:44:28 CET 2023 with GCC 4.7.4)

DEVICE    ADDRESS         IRQ   COMMENT
--------------------------------------------------------------------------------
...
```
I don't pretend to copyright to me the Linux kernel. :-)

**Comment by rick-masters** [comment]
OK, I'll work on a new PR with user_config.h, user_limit.h. I think these files would be generated before running make, not by the Makefile. I will also add them to .gitignore because they are not part of the "standard" source code.
I can also hard code Fiwix in the startup message.

I'll be testing corresponding changes to live-bootstrap with this strategy so that may add some time before I'll have the PR ready.

**Comment by mikaku** [comment]
> OK, I'll work on a new PR with user_config.h, user_limit.h. I think these files would be generated before running make, not by the Makefile.

Perfect.

> I will also add them to .gitignore because they are not part of the "standard" source code. I can also hard code Fiwix in the startup message.

Yes, please.
Thanks.

> I'll be testing corresponding changes to live-bootstrap with this strategy so that may add some time before I'll have the PR ready.

I plan to release the next Fiwix version 1.5.0 on 15 November. Not sure if we have enough time to include all your pending changes in your own Fiwix branch. If not, no problem, we can continue adding your changes into 1.5.0.

**Comment by mikaku** [comment]
That is really neat.
Thank you very much.
