### ISSUE TITLE
Pass through 64-bit PAE memory entries as part of kexec

### ISSUE THREAD

**Issue by rick-masters** [mikaku/Fiwix#67]
Fiwix passes on a memory table as part of the kexec process.
These memory entries should include 64-bit ranges to support [PAE](https://en.wikipedia.org/wiki/Physical_Address_Extension)
This will allow Linux to use more memory in the live-bootstrap project.

The forthcoming PR was originally submitted to the rick-masters fork of Fiwix by @Googulator:
https://github.com/rick-masters/Fiwix/pull/1

**Comment by mikaku** [comment]
Thank you very much.
