### ISSUE TITLE
Please create interim source tarball release for live-bootstrap project

### ISSUE THREAD

**Issue by rick-masters** [mikaku/Fiwix#69]
Live-bootstrap is currently pulling a patched source archive for Fiwix from github.com:rick-masters/Fiwix.
They prefer to use the code from the origin rather than using a fork.
Now that all patches have been incorporated into Fiwix this should be possible.

Therefore, it would be better if you could release a gzipped tar file of source code from your github or website.
Note that currently live-bootstrap has a problem with extracting files from a tarball that start with a period.
So, it is currently necessary to remove the .gitignore file and .git directory before creating the tar file.

I understand that you only do formal releases once in a while. And your releases probably get more stabilization, documentation, and testing. However, live-bootstrap is a faster moving project that tolerates a bit more instability. So, I'd like to suggest that you provide "interim" releases as needed for live-bootstrap. I have been appending -lb1, -lb2, etc. (for live-bootstrap 1, 2, etc) to the current Fiwix release number to identify interim releases supporting live-bootstrap.

It appear you have done a release in github before, but for your convenience, here are the exact steps that can produce a release from GitHub:
* Clone the repo and delete .git and .gitignore
* Create a tarball with .tar.gz extension such as fiwix-1.5.0-lb1.tar.gz
      * Note that live-bootstrap does not support bzip2 until after booting Fiwix.
* Create another tarball with .bz2 extension if you'd like.
* Have the tarballs ready so you can drag and drop into github
* Click on "Releases" on the right and then click on "Draft a new release" near the top
* Click "Choose Tag" and enter a new tag name like v1.5.0-lb1 in the text box
* Enter a title such as "Fiwix 1.5.0 for Live Bootstrap v1"
* Enter a description such as "This is an interim release with changes for Live Bootstrap."
* Drag and drop the tarballs that you created earlier
* Click "Publish Release"

Once you have done this I will submit a change to the live-bootstrap project to reflect the new version and source and all the build changes since the last version.

You deserve tremendous gratitude from me and the live-bootstrap project for working over the past year to get through the 27 PRs that I submitted to Fiwix. Thank you!

**Comment by mikaku** [comment]
Does the files in the tarball need to have inside of a directory named after the tarball (without the `.tar.gz` part) so they will extracted inside that directory?

**Comment by rick-masters** [comment]
Yes there should be a top level directory name with the same name such as fiwix-1.5.0-lb1.

**Comment by mikaku** [comment]
I think the title "This is an interim release with changes for Live Bootstrap" may be misleading. It seems that this version is specific to Live Bootstrap project, but it's not. This release is created as of the last commit 00974ef. I mean, is a version created from the master branch on a specific day. Nothing special.

Do you know a better title? something like: "This is an interim release with changes for Live Bootstrap as of 00974ef"?
I'm not sure if my bad English can confuse even more here.

Any suggestion?

**Comment by rick-masters** [comment]
I think its OK but it might be more clear to say "This is an interim release that includes changes since the last release that can be immediately used by the Live Bootstrap project."

**Comment by mikaku** [comment]
Agreed.

**Comment by mikaku** [comment]
Done.

**Comment by rick-masters** [comment]
I hate to be annoying but the tar is constructed in a way that could be a problem.
It has a 1.5.0-lb1 directory instead of fiwix-1.5.0-lb1. That is different from what live-bootstrap expects.

Also, it is not a big deal, but I think you dropped the tar file into the description instead of the release. It would be slightly better if it was in the assets list, like so:
https://github.com/rick-masters/Fiwix/releases/tag/v1.4.0-lb3

However, the above doesn't really matter.As long as there is a URL it's fine.

**Comment by rick-masters** [comment]
Just to clarify, these are the standard live-bootstrap commands:

```
# Extract
mkdir build src
cd src
ungz --file ${DISTFILES}/${pkg}.tar.gz --output ${pkg}.tar
cd ..

cd build
untar --file ../src/${pkg}.tar
cd ${pkg}
```

pkg would be set to fiwix-1.5.0-lb1 and so the directory should match that.

**Comment by mikaku** [comment]
I'm sorry, my fault. I was too focused on removing any file starting with a dot that didn't pay enough attention to the rest.
Now should all be fixed.

**Comment by rick-masters** [comment]
OK. Looks great! 
Hooray! We did it.

**Comment by Googulator** [comment]
I'm pretty sure bz2 is supported from the very beginning; ungz and unbz2 are built right after each other.

**Comment by mikaku** [comment]
Whatever compress method you decide will be fine for me.
