### ISSUE TITLE
Sync drives on kernel stop

### ISSUE THREAD

**Issue by rick-masters** [mikaku/Fiwix#70]
With live-bootstrap running on Fiwix there are occasionally errors that cause the build process to exit with an error.
Since live-bootstrap runs as init, and will be the last process to exit, the kernel will stop.
For debugging purposes, sometimes I extract the initrd file system from memory and examine it.
This can be done from the qemu console using the pmemsave command.

The problem is that the file system will not be sync'd and so there can be missing files or output.
It would be helpful if the file systems were sync'd before stop_kernel().

I have been using the forthcoming PR in my own testing for many months and it works well for me.

**Comment by mikaku** [comment]
> I have been using the forthcoming PR in my own testing for many months and it works well for me.

Thank you very much.
