### ISSUE TITLE
man page segfaults

### ISSUE THREAD

**Issue by ghaerr** [mikaku/Fiwix#86]
Attempting to display a man page on anything using `man` segfaults. Not sure why.

<img width="832" alt="man" src="https://github.com/mikaku/Fiwix/assets/11985637/dbc8c89e-289a-4c23-9cbc-6b1420b397b8">

[EDIT: Running `mandocdb /usr/share/man` produces the same result].

**Comment by mikaku** [comment]
Yes, I know. This is a known bug by me needs to be investigate.
In fact, it only segfauls when the `man` command doesn't find the man page requested.

**Comment by mikaku** [comment]
I've found a bug in the `glob()` function of the Newlib C library. So I've [sent](https://sourceware.org/pipermail/newlib/2024/021247.html) a patch to its Mailing List.

FiwixOS 3.4 will be released with this bug fixed.
Thanks.
