### ISSUE TITLE
LDFLAGS have erroneous "-no*" flags

### ISSUE THREAD

**Issue by randomouscrap98** [mikaku/Fiwix#97]
When invoking `ld` directly, you don't need to use these flags, as they are gcc only and ignored by ld: `-nostartfiles -nostdlib -nodefaultlibs -nostdinc`. gcc adds additional libraries when invoking ld on your behalf, hence why the flags are required for gcc, but ld doesn't have them because it doesn't add anything you don't specify.

Older versions of ld ignore these flags, as they are interpreted as -n, -o, startfiles (etc) rather than the full flag, which is why I think you didn't get any errors. On newer versions (which I'm using), it is instead an error, and I can't build. See: https://sourceware.org/pipermail/binutils/2021-June/116826.html

I was able to get the kernel to compile by simply removing these flags. I think you may still need them for tcc since you're invoking tcc as the linker, but for gcc you just have to remove the 4 flags:

```make
ifeq ($(CCEXE),gcc)
LD = $(CROSS_COMPILE)ld
CPP = $(CROSS_COMPILE)cpp -P -I$(INCLUDE)
LIBGCC := -L$(shell dirname `$(CC) -print-libgcc-file-name`) -lgcc
LDFLAGS = -m elf_i386
endif
```

**Comment by mikaku** [comment]
Yes, you're right. I think this comes from an old configuration but since I use GCC 4.7.4 I didn't notice it.

**Comment by mikaku** [comment]
Thank you very much.
